

export const classroomsData = [
    { id: 1, name: 'Language Lab' },
    { id: 2, name: 'Classroom 1' },
    { id: 3, name: 'Classroom 2 - AIML Lab (Lab1)' },
    { id: 4, name: 'Classroom 3 - AIDA Lab (Lab2)' },
    { id: 5, name: 'Classroom 4 - CS Lab (Lab3)' },
    { id: 6, name: 'Classroom 5' },
    { id: 7, name: 'Classroom 6' },
    { id: 8, name: 'Classroom 7 - IOT Lab' },
    { id: 9, name: 'Classroom 8' },
    { id: 10, name: 'Classroom 9 - MED Lab' },
    { id: 11, name: 'Classroom 10' },
    { id: 12, name: 'Classroom 11' },
    { id: 13, name: 'Classroom 12' },
    { id: 14, name: 'Classroom 14' },
    { id: 15, name: 'Classroom 15' },
    { id: 16, name: 'Classroom 16' },
    { id: 17, name: 'Classroom 17' },
    { id: 18, name: 'Classroom 18' },
    { id: 19, name: 'Classroom 19' },
    { id: 20, name: 'Classroom 20' },
    { id: 21, name: 'Classroom 21' },
    { id: 22, name: 'Classroom 22' },
    { id: 23, name: 'Physics Lab' },
    { id: 24, name: 'EHS Classroom 1' },
    { id: 25, name: 'EHS Classroom 2' },
    { id: 26, name: 'EHS Classroom 3' },
    { id: 27, name: 'BIO Department' },
];
